name:  Doit Python 0310

on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: python doit
      run: |
        date
        test ! -d ./dist && mkdir ./dist
        ls -al
        pip install bs4 -y        
        python script/web2json-data.py
        ls -al
    - name: publish data json
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: data
