name:  Doit Python 0310

on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        ref: data
        path: data 
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: python doit
      run: |
        pip install bs4
        test ! -d ./data && mkdir ./data
        test ! -d ./data/data && mkdir ./data/data
        test ! -d ./data/news && mkdir ./data/news
        python script/web2json-data.py
        python script/web2json-news.py
    - name: publish data json
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        publish_branch: data
